config/routes.rb
Rails.application.routes.draw do

  get 'registros/verifica_servidor'

  resources :tipo_periodos
  resources :empresas
  resources :niveis do
    member do
      post "/update", :to => "niveis#update1", :as => 'update'
      post "/new_dia_nao_letivo", :to => "niveis#new_dia_nao_letivo", :as => 'new_dia_nao_letivo'
      post "/new_periodo_nao_letivo", :to => "niveis#new_periodo_nao_letivo", :as => 'new_periodo_nao_letivo'
      post "/delete_dia_nao_letivo/:id", :to => "niveis#delete_dia_nao_letivo", :as => 'delete_dia_nao_letivo'
      get 'periodo_nao_letivos', :to => "niveis#periodo_nao_letivos"
      get 'dias_nao_letivos', :to => "niveis#dias_nao_letivos"
      get 'periodos', :to => "niveis#periodos"
      get 'ferias', :to => "niveis#ferias"
      get 'tipo_periodos', :to => 'niveis#tipo_periodos'
      get 'series', :to =>'niveis#series'
    end
  end
  post '/niveis/new', :to =>'niveis#create', :as =>'nivel_new', :via => 'POST'
  resources :series do
    member do
      post "/update", :to => "series#update", :as => 'update'
      get 'turmas', :to =>'series#turmas', :as => 'series_turmas'
    end
  end
  post '/series/new', :to =>'series#create', :as =>'series_new', :via => 'POST'

  resources :turmas do

    member do
      get 'show_limited', :to => 'turmas#show'
      post '/alunos/import', :to =>'alunos#import_por_turma', :as =>'alunos_import', :via => 'POST'
      post "/update", :to => "turmas#update", :as => 'update'
      get 'alunos', :to => 'turmas#alunos'
      get 'aulas', :to => 'turmas#aulas'
      get 'dia_semana_aulas', :to => 'turmas#dia_semana_aulas'
      post '/new_aula', :to => 'turmas#new_aula'

    end

  end
  post '/turmas/new', :to =>'turmas#create', :as =>'turmas_new', :via => 'POST'
  get '/turmas/aula/:id_aula', :to => "turmas#aula"
  post '/update/aula', :to => "turmas#update_aula"
  resources :aulas do
  end

  resources :periodos do
    member do
      post "/update", :to => "periodos#update", :as => 'update'
    end
  end
  post '/periodos/new', :to =>'periodos#create', :as =>'periodos_new', :via => 'POST'

  resources :alunos do
    member do
      post "/update", :to => "alunos#update", :as => 'update'
      get '/historico', :to => "alunos#historico"
    end
  end
  #get '/all_alunos', :to => 'alunos#all_alunos', :as => 'all_alunos'
  post '/alunos/new', :to =>'alunos#create', :as =>'alunos_new', :via => 'POST'
  post '/alunos/import', :to =>'alunos#import', :as =>'alunos_import', :via => 'POST'
  get 'alunos_semturma', :to => 'alunos#alunos_semturma', :as => 'alunos_semturma'
  post 'adiciona_aluno_turma_path', :to => 'alunos#adiciona_aluno_turma', :as => 'adiciona_aluno_turma'

  resources :etiquetas do
    member do

    end

  end
  get '/etiquetas_por_aluno/:aluno_id', :to => "etiquetas#etiquetas_por_aluno", :as => "etiquetas_por_aluno"

  devise_for :users, :path_prefix => 'devise', :skip => [:api, :registros]
  devise_scope :user do
    get '/logout',  :to => 'devise/sessions#destroy'
  end
  resources :users do
    member do
      
    end
  end
  post 'update_user', :to => 'users#update', :as => 'update_user'
  
  resources :dashboard
  get 'calendario' => 'dashboard#calendario'

  resources :registros

  root 'dashboard#index'
  get 'menu_xml' => 'menu#menu_xml'
  get 'horas' => 'menu#horas'
  get 'minutos' => 'menu#minutos'
  get 'niveis_toolbar' => 'niveis#niveis_toolbar'
  get 'admin' => 'dashboard#admin'

  match "tipo_periodos/db_action", :to => "tipo_periodos#db_action", :as => "tipo_periodos_db_action", :via =>"post"
  match "users/db_action", :to => "users#db_action", :as => "users_db_action", :via =>"post"
  match "alunos/db_action", :to => "alunos#db_action", :as => "alunos_db_action", :via =>"post"
  match "etiquetas/db_action", :to => "etiquetas#db_action", :as => "etiquetas_db_action", :via =>"post"
  match "niveis/db_action", :to => "niveis#db_action", :as => "niveis_db_action", :via =>"post"
  match "series/db_action", :to => "series#db_action", :as => "series_db_action", :via =>"post"
  match "turmas/db_action", :to => "turmas#db_action", :as => "turmas_db_action", :via =>"post"
  match "turmas/db_action_alunos", :to => "turmas#db_action_alunos", :as => "turmas_db_action_alunos", :via =>"post"
  match "turmas/db_action_aulas", :to => "turmas#db_action_aulas", :as => "turmas_db_action_aulas", :via =>"post"
  match "niveis/db_action_dias_nao_letivos", :to => "niveis#db_action_dias_nao_letivos", :as => "niveis_db_action_dias_nao_letivos", :via =>"post"
  match "niveis/db_action_periodo_nao_letivos", :to => "niveis#db_action_periodo_nao_letivos", :as => "niveis_db_action_periodo_nao_letivos", :via =>"post"
  match "niveis/db_action_periodos", :to => "niveis#db_action_periodos", :as => "niveis_db_action_periodos", :via =>"post"




  #Api
  namespace :api do
    root 'api#index'
    resources :registros do
      #match "upload_file", :to => "registros#upload_file", :via => "post"
      collection do
        get "upload_file"
        post "upload_file"
        post "upload_file_line"
      end
    end
  end

  namespace :mobile do

  end
end

app/models/turma.rb
class Turma < ActiveRecord::Base
  belongs_to :serie
  has_many :alunos
end

app/controllers/turmas_controller.rb
class TurmasController < ApplicationController
  before_action :set_registro, only: [:show, :show_limited, :edit, :update, :destroy, :dias_nao_letivos,
    :periodo_nao_letivos, :alunos, :dia_semana_aulas, :aulas]
  before_action :set_listagem, only: [:index]
  respond_to :html, :xml, :json
  protect_from_forgery :except => [:create, :update, :db_action, :db_action_alunos,
    :dia_semana_aulas, :new_aula, :db_action_aulas, :update_aula]

  def index
    respond_with(@turmas)
  end

  def new
    @turma = Serie.new(turmas_params)
  end
  def show

  end
  def show_limited
  end

  def edit
    #@nivel.dias_nao_letivos.build
    respond_with(@turma)
  end

  def create
    #logger.debug nivel_params
    @record = Turma.new(turmas_params)
    if(@record.save)
      respond_to do |format|
         format.json { render json: {:message => 'Cadastrado com sucesso!'}, status: 200}
      end
    end
    #respond_to do |format|
    #  format.html { render 'new', notice: 'Erro ao cadastradar!'}
    #end
  end

  def update
    logger.info 'entoru no update info'
    if(@turma.update(turmas_params))
      respond_to do |format|
         format.json { render json: {:message => 'Atualizado com sucesso!'}, status: 200}
      end
    end
  end

  def db_action
    @mode = params["!nativeeditor_status"]
    case @mode
    when "inserted"

    when "deleted"
      @record = Turma.find(params[:gr_id])
      @record.destroy
    end
  end

  #Aulas
  def aulas
    @aulas = Aula.all.where(turma: params[:id]).order(:dia_semana, :horario_inicio)
  end

  def aula
    logger.info params
    @aula = Aula.find(params[:id_aula])
  end

  def update_aula
    logger.info params
    new_aula()
  end

  def dia_semana_aulas
    @dias = @turma.serie.nivel.dias_semana_letivo.split(',')
    logger.info @dias
  end

  def new_aula
    #@record = Aula.new(aulas_params)
    @record = Aula.where(id: params[:id_aula]).first_or_initialize
    @record.attributes = aulas_params
    @record[:horario_inicio] = Time.new(0,01,01,params[:hora_entrada],params[:minuto_entrada],0).to_s(:time)
    @record[:horario_termino] = Time.new(0,01,01,params[:hora_saida],params[:minuto_saida],0).to_s(:time)


    logger.info 'vai tentar salvar'
    if(@record.save)
      respond_to do |format|
         format.json { render json: {:message => 'Cadastrado com sucesso!'}, status: 200}
      end
    else
      logger.info 'nao salvou'
      logger.info @record.errors[:aula][0]
      respond_to do |format|
        format.json { render json: {:message => "Houve um erro ao cadastrar a aula! : #{@record.errors[:aula][0]} ."}, status: 400}
      end

    end
  end

  def db_action_aulas
    @mode = params["!nativeeditor_status"]
    case @mode
    when "deleted"
      @record = Aula.find(params[:gr_id])
      @record.destroy
    end

    respond_to do |format|
      format.xml { render :db_action }
    end

  end

  #Alunos
  def alunos
    @alunos = Aluno.all.where(turma: params[:id]).order(:nome)
  end

  def db_action_alunos
    @mode = params["!nativeeditor_status"]
    case @mode
    when "updated"
      @record = Aluno.find(params[:gr_id])
      if(@record.update(alunos_params))

      else
        @mode = 'error'
        @erro = 'Algo não deu certo =/'
      end
    when "deleted"
      @record = Aluno.find(params[:gr_id])
      @record.turma = nil
      @record.save
    end

  end

  private
  def set_listagem
    @turmas = Turma.all.order(:created_at)
  end

  def set_registro
    @turma = Turma.find(params[:id])
  end

  def turmas_params
    params.permit(:titulo, :serie_id, :created_at, :updated_at)
  end

  def aulas_params
    params.permit(:titulo, :horario_inicio, :horario_termino, :turma_id, :dia_semana, :created_at, :updated_at)
  end

  def alunos_params
    params.permit(:id, :codigo, :nome, :rg, :cpf, :nome_mae, :telefone_mae, :celular_mae, :email_mae,
                  :nome_pai, :telefone_pai, :celular_pai, :email_pai, :created_at, :updated_at, :turma_id)
  end


end

app/views/turmas/aulas.html.erb
<script>
	dhtmlxEvent(window,"load", function(id){
		//var layout = new dhtmlXLayoutObject(document.body, "2E");
		var layout = new dhtmlXLayoutObject('aulas', "1C");
		layout.cells("a").hideHeader();


		mygrid = layout.cells("a").attachGrid();
		mygrid.loadXML("aulas.xml", function() {
			mygrid.groupBy(3);
		});
		mygrid.setImagePath("/assets/dhtmlx/");
		//mygrid.setColumnIds("motivo,dia");
		mygrid.enableAutoWidth(true);
		mygrid.enableEditEvents(false,false,false);
		mygrid.init();

		dp = new dataProcessor('<%= turmas_db_action_aulas_path %>');
		dp.init(mygrid);
		dp.setTransactionMode("POST");

		toolbar = new dhtmlXToolbarObject({
    		parent:"my_toolbar_here",
    		icons_path: "/assets/dhtmlx/",
		    items:[
		        {id: "new", type: "button", text: "Novo", img: "new.gif"},
		        {id: "delete", type: "button", text:'Remover', img: "trash_delete.gif"},
						{id: "edit", type: "button", text:'Editar', img: "edit.png"},
		    ],
		    onClick:function(id){
		    	if(id == 'new') {
		    		var myWins= new dhtmlXWindows();
		    		myWins.createWindow('new_aula', 50, 25, 360,400);
		    		myWins.window('new_aula').setText('Novo registro');
		    		myWins.window('new_aula').setModal(true);
		    		myWins.window('new_aula').denyResize();
		    		myWins.window('new_aula').denyPark();

		    		formStructure = [
					    {type:"settings",position:"label-top"},
					    {type: "block", name:'nivel', list:[
						    {type: "fieldset",name:"nivel", width:300, label: "Novo registro", list:[

										{type: "hidden", name: 'turma_id', value: '<%= @turma.id %>'},
						        {type: "input", width: 200, name: 'titulo', label: 'Titulo:', validate: "NotEmpty", required: true},
										{type: "combo", width: 200, name: 'dia_semana', readonly: true, label: 'Dia da semana', required: true, options:[]},
						       	{type: "label",className: 'label_form',label: "Entrada"},
						       		{type: "block", name:'nivel', blockOffset: 0, list:[
							        {type:"combo", className:'time', width: 60, name:"hora_entrada",label:"Hora",
												readonly:true, validate: "NotEmpty", required: true, options :[]},
							        {type: "newcolumn", offset:30},
							        {type:"combo",inputTop:15, className:'time', width: 60, name:"minuto_entrada",readonly:true, label:"Minutos",
							        	validate: "NotEmpty", required: true, readonly:true, options:[]},
						        ]},
						        {type: "block", name:'nivel', blockOffset: 0, list:[
						       		{type: "label",className: 'label_form',label: "Saida"},
						       	]},
						       {type: "block", name:'nivel', blockOffset: 0, list:[
							        {type:"combo", className:'time', width: 60, name:"hora_saida",label:"Hora",
												validate: "NotEmpty", required: true, readonly:true,options :[]},
							        {type: "newcolumn", offset:30},
							        {type:"combo", className:'time', width: 60, name:"minuto_saida",label:"Minutos",
							        	validate: "NotEmpty", required: true,readonly:true, options:[]},
						        ]},
								{type: "block", name:'nivel', list:[
									{type: "button", inputLeft: 10, name: "save", value: "Adicionar"},
									{type: "button", position:'absolute',inputLeft:105,inputTop:6, name: "cancel", value: "Cancelar"},
								]},
						    ]}
						 ]},
					];


		    		new_register = myWins.window('new_aula').attachForm(formStructure);
					new_register.reloadOptions("dia_semana", 'dia_semana_aulas');
					new_register.reloadOptions("hora_entrada", '/horas');
					new_register.reloadOptions("minuto_entrada", '/minutos');
					new_register.reloadOptions("hora_saida", '/horas');
					new_register.reloadOptions("minuto_saida", '/minutos');

					new_register.attachEvent("onButtonClick", function(name, command) {
							if(name == 'save') {
								this.send('<%= new_aula_turma_path(@turma)  %>', function(loader, response){
									if(loader.xmlDoc.status == 400) {
										var erro = $.parseJSON(response)
										dhtmlx.alert({
											title:"Não foi possivel cadastrar aula.",
											type:"alert-error",
											text: erro.message
										});
									}else {
							      myWins.window('new_aula').close();
							      mygrid.updateFromXML('aulas.xml', true, true, function() {
											mygrid.groupBy(3);
										});
									}
						    });
							}else if(name == 'cancel') {
								myWins.window('new_aula').close();
							}
						});

		    	}else if(id == 'delete') {
		    			var selectedRow = mygrid.getSelectedId();
			    		if(selectedRow > 0) {
							dhtmlx.confirm({
							    title: "Tem certeza?",
							    text: "Você tem certeza que deseja excluir este registo??",
							    callback: function(name) {
							    	if(name) {
							    		mygrid.deleteSelectedItem();
											mygrid.groupBy(3);
							    	}
							    }
							});
						}else {
							dhtmlx.message({
							    text:"Você não selecionou nenhum registro para excluir!",
							    expire:1000
							});
						}
		    	}else if(id == 'edit') {
						var selectedRow = mygrid.getSelectedId();
						if(selectedRow > 0) {
							console.log(selectedRow);

							var myWins= new dhtmlXWindows();

			    		myWins.createWindow('new_aula', 50, 25, 360,400);
			    		myWins.window('new_aula').setText('Novo registro');
			    		myWins.window('new_aula').setModal(true);
			    		myWins.window('new_aula').denyResize();
			    		myWins.window('new_aula').denyPark();

			    		formStructure = [
						    {type:"settings",position:"label-top"},
						    {type: "block", name:'nivel', list:[
							    {type: "fieldset",name:"nivel", width:300, label: "Novo registro", list:[

											{type: "hidden", name: 'turma_id', value: '<%= @turma.id %>'},
							        {type: "input", width: 200, name: 'titulo', label: 'Titulo:', validate: "NotEmpty", required: true},
											{type: "combo", width: 200, name: 'dia_semana', readonly: true, label: 'Dia da semana', required: true, options:[]},
							       	{type: "label",className: 'label_form',label: "Entrada"},
							       		{type: "block", name:'nivel', blockOffset: 0, list:[
								        {type:"combo", className:'time', width: 60, name:"hora_entrada",label:"Hora",
													readonly:true, validate: "NotEmpty", required: true, options :[]},
								        {type: "newcolumn", offset:30},
								        {type:"combo",inputTop:15, className:'time', width: 60, name:"minuto_entrada",readonly:true, label:"Minutos",
								        	validate: "NotEmpty", required: true, readonly:true, options:[]},
							        ]},
							        {type: "block", name:'nivel', blockOffset: 0, list:[
							       		{type: "label",className: 'label_form',label: "Saida"},
							       	]},
							       {type: "block", name:'nivel', blockOffset: 0, list:[
								        {type:"combo", className:'time', width: 60, name:"hora_saida",label:"Hora",
													validate: "NotEmpty", required: true, readonly:true,options :[]},
								        {type: "newcolumn", offset:30},
								        {type:"combo", className:'time', width: 60, name:"minuto_saida",label:"Minutos",
								        	validate: "NotEmpty", required: true,readonly:true, options:[]},
							        ]},
									{type: "block", name:'nivel', list:[
										{type: "button", inputLeft: 10, name: "save", value: "Salvar"},
										{type: "button", position:'absolute',inputLeft:105,inputTop:6, name: "cancel", value: "Cancelar"},
									]},
							    ]}
							 ]},
						];


			    	new_register = myWins.window('new_aula').attachForm(formStructure);
					new_register.reloadOptions("dia_semana", 'dia_semana_aulas');
					new_register.reloadOptions("hora_entrada", '/horas');
					new_register.reloadOptions("minuto_entrada", '/minutos');
					new_register.reloadOptions("hora_saida", '/horas');
					new_register.reloadOptions("minuto_saida", '/minutos');

					new_register.load('/turmas/aula/'+selectedRow);
					new_register.attachEvent("onButtonClick", function(name, command) {
							if(name == 'save') {
								this.send('<%= update_aula_path  %>', function(loader, response){
									if(loader.xmlDoc.status == 400) {
										var erro = $.parseJSON(response)
										dhtmlx.alert({
											title:"Não foi possivel atualizar aula.",
											type:"alert-error",
											text: erro.message
										});
									}else {
							      myWins.window('new_aula').close();
							      mygrid.updateFromXML('aulas.xml', true, true, function() {
											mygrid.groupBy(3);
										});
									}
						    });
							}else if(name == 'cancel') {
								myWins.window('new_aula').close();
							}
						});



					}else {
						dhtmlx.message({
						    text:"Você não selecionou nenhum registro para editar!",
						    expire:1500
						});
					}
				}
		    }
		});

	});
</script>
<style>
	html, body, #aulas {
	        width: 100%;      /*provides the correct work of a full-screen layout*/
	        height: 100%;     /*provides the correct work of a full-screen layout*/
	        overflow: hidden; /*hides the default body's space*/
	        margin: 0px;      /*hides the body's scrolls*/
	    }
</style>
<div id='my_toolbar_here' style="width: 100%;"></div>
<div id="aulas"></div>

app/views/turmas/db_action.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<data>
	<action type="<%= @mode %>" sid="<%= @record.id %>" tid="<%= @tid %>" />
</data>

app/views/turmas/db_action_alunos.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<data>
	<action type="<%= @mode %>" sid="<%= @record.id %>" tid="<%= @tid %>" />
</data>

app/views/turmas/show.html.erb
<%= csrf_meta_tags %>
<script>
	dhtmlxEvent(window,"load", function(id){

		//var layout = new dhtmlXLayoutObject(document.body, "2E");
		var layout = new dhtmlXLayoutObject(document.body, "1C");

		//layout.cells("a").setText("Detalhes da turma");//sets the form's header
		var tabbar = layout.cells("a").attachTabbar({
			icons_path: "/assets/dhtmlx/"
		});

		//Carrega a segunda aba dos alunos
		var tab = tabbar.addTab(
	    'alunos',       // id
	    'Alunos',    // tab text
	    null,       // auto width
	    null,       // last position
	    false,      // inactive
	    false       // disable close button <-- this one
		);

		 //Adiciona a lista de alunos
		 mygrid =  tabbar.cells('alunos').attachURL('<%= alunos_turma_path(@turma) %>');

		//Seta a tab como ativa
		tabbar.tabs('alunos').setActive();

		//if(parent.getPerfil() != 'admin') {

			var tab = tabbar.addTab(
		    'detalhes_turma',       // id
		    'Detalhes da turma',    // tab text
		    null,       // auto width
		    null,       // last position
		    false,      // inactive
		    false       // disable close button <-- this one
			);

			
			//Configura o formulario
			formStructure = [
			    {type:"settings",position:"label-top"},
			    {type: "block", width: 900, name:'nivel', list:[
				    {type: "fieldset",name:"nivel", width:900, label: "Detalhes", list:[
				        {type: "hidden", name: 'id'},
				        {type: "input", width: 300, name: 'titulo', label: 'Titulo:'},
								{type:"container", name:"aulas", label:"Horário das aulas", inputWidth:500, inputHeight:450},
						{type: "button", name: "save", value: "Salvar mudanças"},
				    ]}
				 ]}
			];

			//Adiciona a tab com o formulario
			myForm = tabbar.cells('detalhes_turma').attachForm(formStructure);
			myForm.attachEvent("onButtonClick", function(name, command) {
				if(name == 'save') {
					this.send('<%= update_turma_path(@turma) %>', function(loader, response) {
						dhtmlx.message({
						    text:"Registro atualizado com sucesso!",
						    expire:2000
						});
					});
					parent.atualiza_menu();

				}
			});

			//Carrega os dados no formulario
			myForm.load('<%= edit_turma_path(@turma, :format => 'xml')  %>');

			//Carrega as aulas da turma
			aulas = new dhtmlXLayoutObject(myForm.getContainer("aulas"),"1C");
			aulas.cells('a').hideHeader();
			aulas.cells('a').attachURL('<%= aulas_turma_path(@turma);  %>');
		//}
		
	});
</script>
<style>
	html, body, #gridbox {
	        width: 100%;      /*provides the correct work of a full-screen layout*/
	        height: 100%;     /*provides the correct work of a full-screen layout*/
	        overflow: hidden; /*hides the default body's space*/
	        margin: 0px;      /*hides the body's scrolls*/
	    }
</style>

<div id="gridbox"></div>
<div id='form_container'></div>
<div id="turmas"></div>

app/views/turmas/show_limited.html.erb
<%= csrf_meta_tags %>
<script>
	dhtmlxEvent(window,"load", function(id){
		//var layout = new dhtmlXLayoutObject(document.body, "2E");
		var layout = new dhtmlXLayoutObject(document.body, "1C");

		//layout.cells("a").setText("Detalhes da turma");//sets the form's header
		var tabbar = layout.cells("a").attachTabbar({
			icons_path: "/assets/dhtmlx/"
		});

		//Carrega a segunda aba dos alunos
		var tab = tabbar.addTab(
	    'alunos',       // id
	    'Alunos',    // tab text
	    null,       // auto width
	    null,       // last position
	    false,      // inactive
	    false       // disable close button <-- this one
		);

		 //Adiciona a lista de alunos
		 mygrid =  tabbar.cells('alunos').attachURL('<%= alunos_turma_path(@turma) %>');
		 /*
		*/

		//Seta a tab como ativa
		tabbar.tabs('alunos').setActive();
		//Configura o formulario
		formStructure = [
		    {type:"settings",position:"label-top"},
		    {type: "block", width: 900, name:'nivel', list:[
			    {type: "fieldset",name:"nivel", width:900, label: "Detalhes", list:[
			        {type: "hidden", name: 'id'},
			        {type: "input", width: 300, name: 'titulo', label: 'Titulo:'},
							{type:"container", name:"aulas", label:"Horário das aulas", inputWidth:500, inputHeight:450},
					{type: "button", name: "save", value: "Salvar mudanças"},
			    ]}
			 ]}
		];

	});
</script>
<style>
	html, body, #gridbox {
	        width: 100%;      /*provides the correct work of a full-screen layout*/
	        height: 100%;     /*provides the correct work of a full-screen layout*/
	        overflow: hidden; /*hides the default body's space*/
	        margin: 0px;      /*hides the body's scrolls*/
	    }
</style>

<div id="gridbox"></div>
<div id='form_container'></div>
<div id="turmas"></div>