config/routes.rb
Rails.application.routes.draw do

  get 'registros/verifica_servidor'

  resources :tipo_periodos
  resources :empresas
  resources :niveis do
    member do
      post "/update", :to => "niveis#update1", :as => 'update'
      post "/new_dia_nao_letivo", :to => "niveis#new_dia_nao_letivo", :as => 'new_dia_nao_letivo'
      post "/new_periodo_nao_letivo", :to => "niveis#new_periodo_nao_letivo", :as => 'new_periodo_nao_letivo'
      post "/delete_dia_nao_letivo/:id", :to => "niveis#delete_dia_nao_letivo", :as => 'delete_dia_nao_letivo'
      get 'periodo_nao_letivos', :to => "niveis#periodo_nao_letivos"
      get 'dias_nao_letivos', :to => "niveis#dias_nao_letivos"
      get 'periodos', :to => "niveis#periodos"
      get 'ferias', :to => "niveis#ferias"
      get 'tipo_periodos', :to => 'niveis#tipo_periodos'
      get 'series', :to =>'niveis#series'
    end
  end
  post '/niveis/new', :to =>'niveis#create', :as =>'nivel_new', :via => 'POST'
  resources :series do
    member do
      post "/update", :to => "series#update", :as => 'update'
      get 'turmas', :to =>'series#turmas', :as => 'series_turmas'
    end
  end
  post '/series/new', :to =>'series#create', :as =>'series_new', :via => 'POST'

  resources :turmas do

    member do
      get 'show_limited', :to => 'turmas#show'
      post '/alunos/import', :to =>'alunos#import_por_turma', :as =>'alunos_import', :via => 'POST'
      post "/update", :to => "turmas#update", :as => 'update'
      get 'alunos', :to => 'turmas#alunos'
      get 'aulas', :to => 'turmas#aulas'
      get 'dia_semana_aulas', :to => 'turmas#dia_semana_aulas'
      post '/new_aula', :to => 'turmas#new_aula'

    end

  end
  post '/turmas/new', :to =>'turmas#create', :as =>'turmas_new', :via => 'POST'
  get '/turmas/aula/:id_aula', :to => "turmas#aula"
  post '/update/aula', :to => "turmas#update_aula"
  resources :aulas do
  end

  resources :periodos do
    member do
      post "/update", :to => "periodos#update", :as => 'update'
    end
  end
  post '/periodos/new', :to =>'periodos#create', :as =>'periodos_new', :via => 'POST'

  resources :alunos do
    member do
      post "/update", :to => "alunos#update", :as => 'update'
      get '/historico', :to => "alunos#historico"
    end
  end
  #get '/all_alunos', :to => 'alunos#all_alunos', :as => 'all_alunos'
  post '/alunos/new', :to =>'alunos#create', :as =>'alunos_new', :via => 'POST'
  post '/alunos/import', :to =>'alunos#import', :as =>'alunos_import', :via => 'POST'
  get 'alunos_semturma', :to => 'alunos#alunos_semturma', :as => 'alunos_semturma'
  post 'adiciona_aluno_turma_path', :to => 'alunos#adiciona_aluno_turma', :as => 'adiciona_aluno_turma'

  resources :etiquetas do
    member do

    end

  end
  get '/etiquetas_por_aluno/:aluno_id', :to => "etiquetas#etiquetas_por_aluno", :as => "etiquetas_por_aluno"

  devise_for :users, :path_prefix => 'devise', :skip => [:api, :registros]
  devise_scope :user do
    get '/logout',  :to => 'devise/sessions#destroy'
  end
  resources :users do
    member do
      
    end
  end
  post 'update_user', :to => 'users#update', :as => 'update_user'
  
  resources :dashboard
  get 'calendario' => 'dashboard#calendario'

  resources :registros

  root 'dashboard#index'
  get 'menu_xml' => 'menu#menu_xml'
  get 'horas' => 'menu#horas'
  get 'minutos' => 'menu#minutos'
  get 'niveis_toolbar' => 'niveis#niveis_toolbar'
  get 'admin' => 'dashboard#admin'

  match "tipo_periodos/db_action", :to => "tipo_periodos#db_action", :as => "tipo_periodos_db_action", :via =>"post"
  match "users/db_action", :to => "users#db_action", :as => "users_db_action", :via =>"post"
  match "alunos/db_action", :to => "alunos#db_action", :as => "alunos_db_action", :via =>"post"
  match "etiquetas/db_action", :to => "etiquetas#db_action", :as => "etiquetas_db_action", :via =>"post"
  match "niveis/db_action", :to => "niveis#db_action", :as => "niveis_db_action", :via =>"post"
  match "series/db_action", :to => "series#db_action", :as => "series_db_action", :via =>"post"
  match "turmas/db_action", :to => "turmas#db_action", :as => "turmas_db_action", :via =>"post"
  match "turmas/db_action_alunos", :to => "turmas#db_action_alunos", :as => "turmas_db_action_alunos", :via =>"post"
  match "turmas/db_action_aulas", :to => "turmas#db_action_aulas", :as => "turmas_db_action_aulas", :via =>"post"
  match "niveis/db_action_dias_nao_letivos", :to => "niveis#db_action_dias_nao_letivos", :as => "niveis_db_action_dias_nao_letivos", :via =>"post"
  match "niveis/db_action_periodo_nao_letivos", :to => "niveis#db_action_periodo_nao_letivos", :as => "niveis_db_action_periodo_nao_letivos", :via =>"post"
  match "niveis/db_action_periodos", :to => "niveis#db_action_periodos", :as => "niveis_db_action_periodos", :via =>"post"




  #Api
  namespace :api do
    root 'api#index'
    resources :registros do
      #match "upload_file", :to => "registros#upload_file", :via => "post"
      collection do
        get "upload_file"
        post "upload_file"
        post "upload_file_line"
      end
    end
  end

  namespace :mobile do

  end
end

app/views/users_old/_form.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="box box-primary">
		    <div class="box-header">
		        <h3 class="box-title">Novo Usuário</h3>
		    </div>
			<%= form_for(@user, :html => { :role => "form"}) do |f| %>
				<div class="col-md-12">
			  		<div id='error_messages'></div>
			  	</div>
			  	<% if @user.errors.any? %>
			    	<div id="error_explanation">
				  		<div class="alert alert-danger" role="alert">
				  			<strong>Erro salvar usuário!</strong>
					  		<br/><br/>
					    	<ul>
						    	<% @user.errors.full_messages.each do |message| %>
						        	<li><%= message %></li>
						      	<% end %>
					    	</ul>
				   		</div>
			    	</div>
			  <% end %>
			  <div class="box-body">
			  	<div class="form-group">
	                <%= f.label :nome, 'Nome'%>
	                <%= f.text_field :nome, :class =>"form-control", :placeholder=> :nome %>
	            </div>
	            <div class="form-group">
	                <%= f.label :email, 'Email' %>
	                <%= f.email_field :email, :class =>"form-control", :placeholder=> :email %>
	            </div>
	            <div class="form-group">
	                <%= f.label :password, 'Senha' %>
	                <%= f.password_field :password, :class =>"form-control", :placeholder=> :senha %>
	            </div>
	            <div class="form-group">
	                <%= f.label :password_confirmation, 'Confirme sua senha'%>
	                <%= f.password_field :password_confirmation, :class =>"form-control", :placeholder=> 'Confirme sua senha' %>
	            </div>
	            <div class="form-group">
	                <%= f.label :status %>
	                <%= f.select :status, options_for_select([['Ativo'],['Inativo']], selected: @user.status), {}, :class =>" form-control combo" %>
	            </div>
			  </div>
			  <div class="box-footer">
			  	<%= f.submit 'Salvar', :class => "btn btn-primary" %>
			  	<%= link_to 'Cancelar', '#', :id => 'Cancel', :class => "btn_fechar btn btn-cancel" %>
	          </div>
		   </div>
			<% end %>
		</div>
</div>


<!-- 
	
<div class="box box-primary">
    <div class="box-header">
        <h3 class="box-title">Quick Example</h3>
    </div>
    <form role="form">
        <div class="box-body">
            <div class="form-group">
                <label for="exampleInputEmail1">Email address</label>
                <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
            </div>
            <div class="form-group">
                <label for="exampleInputFile">File input</label>
                <input type="file" id="exampleInputFile">
                <p class="help-block">Example block-level help text here.</p>
            </div>
            <div class="checkbox">
                <label>
                    <div class="icheckbox_minimal" aria-checked="false" aria-disabled="false" style="position: relative;"><input type="checkbox" style="position: absolute; opacity: 0;"><ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);"></ins></div> Check me out
                </label>
            </div>
        </div>

        <div class="box-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>
	
	
-->

app/views/users_old/_registros.html.erb
<h1>Tipos de Pagamento Cadastrados</h1>

<div class="row">
	<div class="table-responsive col-md-12">
		<%= grid(@users) do |g|
			
			g.blank_slate  do
		    	content_tag :div, "Nenhum registro encontrado", class: 'well'
		  	end
			
			g.column name: 'Ações', class: 'acoes' do |option|
				buffer =  link_to('', edit_user_path(option), :class => 'editar')
				buffer += link_to('', user_path(option),:class => 'excluir', method: :delete, data: {confirm: 'Você tem certeza?'})
				raw buffer
			end
			
			g.column name: 'Nome', attribute: 'nome', filter: false
			g.column name: 'Email', attribute: 'email', filter: false
			g.column name: 'Criado em', attribute: 'created_at' , filter: false do |user|
				user.created_at.strftime('%d/%m/%Y') if !user.created_at.nil?
			end
			g.column name: 'Ultima vez logado', attribute: 'last_sign_in_at' , filter: false do |user|
				user.last_sign_in_at.strftime('%d/%m/%Y') if !user.last_sign_in_at.nil?
			end			
	    end %>
	</div>

</div>

app/views/users_old/db_action.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<data>
	<action type="<%= @mode %>" sid="<%= @record.id %>" tid="<%= @record.id %>">
		<%= (@erro) ? @erro : '' %>
	</action>
</data>

app/views/users_old/edit.html.erb
<section class="content-header">
	<h1>Editar dados</h1>
	<ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li><%= link_to users_path do %><i class="fa fa-users"></i> Usuarios<% end %></li>
        <li class="active fa fa-user">Novo</li>
    </ol>  
</section>
<section class="content">
	<div class="row">
		<div class="col-md-6">
			<%= render 'form' %>
		</div>
	</div>
</section>

app/views/users_old/index.html.erb
	<script>
		var mygrid;
		var rowIdClicked;
		dhtmlxEvent(window,"load", function(id){
			var layout = new dhtmlXLayoutObject(document.body, "1C");
			layout.cells('a').hideHeader();

			toolbar = layout.cells('a').attachToolbar({
				icons_path: "/assets/dhtmlx/",
				items: [
				{id: "new_user", type: "button", text: "Novo usuário", img: "new.gif"},
				{id: "editar", type: "button", text: "Editar", img: "edit.png"},
				{id: "delete", type: "button", text: "Excluir usuário", img: "remove.gif"}],
					onClick:function(id){
						onClickGrid(id);
					},
				});

			//Context Menu
			var contextMenu = new dhtmlXMenuObject();
			contextMenu.setIconsPath("/assets/dhtmlx/");
			contextMenu.renderAsContextMenu();
			contextMenu.attachEvent("onClick",function(id) {
				onClickGrid(id);
			});
			
			contextMenu.loadFromHTML("contextArea", true);
			
			//Cria a listagem
			mygrid =  layout.cells('a').attachGrid();
			mygrid.enableAutoWidth(true);
			mygrid.setHeader("Nome,Status, Perfil, Email, Ultima vez logado");
			mygrid.setColumnIds("nome,status,role,email,last_sign_in_at");
			mygrid.setColSorting("str,str,str,str,str");
			//mygrid.setColTypes("edn,ed,ed,ed,ed,ed,ro");
			mygrid.attachHeader("#text_filter,#combo_filter,#combo_filter,#text_filter,&nbsp;");
			mygrid.setNumberFormat("000000",0,"","");
			mygrid.enableEditEvents(false,false,false);
			mygrid.enableStableSorting(true);
			mygrid.enableContextMenu(contextMenu);
			mygrid.attachEvent("onRightClick",function (rowId, cellId) {
				rowIdClicked = rowId;
				return true;
			});
			mygrid.init();
			mygrid.load('<%= users_path(:format =>:xml) %>','xml');

			
			
			//Conexão com o servidor
			dp = new dataProcessor('<%= users_db_action_path %>');
			dp.enableDataNames(true);
			//dp.enablePartialDataSend(true);
			
			dp.init(mygrid);
			dp.setTransactionMode("POST");
			dp.defineAction("error", retorno_erro);


		});

	function retorno_erro(retorno) {
		dhtmlx.alert({
			title:"Ops, algo deu errado!",
			type:"alert-error",
			text:"O seguinte erro aconteceu: "+retorno.firstChild.data
		});
		mygrid.updateFromXML('<%= users_path(:format =>:xml) %>');
	}
	function onClickGrid(id) {
		if(id == 'new_user' || id == 'editar') {
			var myWins= new dhtmlXWindows();
			myWins.createWindow('new_user', 240, 75, 400,380);
			myWins.window('new_user').setText('Novo Usuário do sistema');
			myWins.window('new_user').setModal(true);
			myWins.window('new_user').denyResize();
			myWins.window('new_user').denyPark();

			formStructure = [
					{type:"settings",position:"label-top"},
					{type: "block", name:'nivel', list:[
					{type: "fieldset",name:"nivel",width:350, label: "Novo registro", list:[

						{type: "input", width: 310, name: 'nome', label: 'Nome', validate: "NotEmpty", required: true},
						{type: "input", width: 310, name: 'email', label: 'Email', validate: "NotEmpty", required: true},
						{type: "password", width: 310, name: 'password', label: 'Senha'},
						{type: "select", width: 310, name: 'role', label: 'Perfil', validate: "NotEmpty", required: true, options:[
							{text: "Admin", value: "admin"},
				            {text: "Secretaria", value: "scretaria"},
				            {text: "Professor", value: "professor"}
						]},
						{type: "select", width: 310, name: 'status', label: 'Status', validate: "NotEmpty", required: true, options:[
							{text: "Ativo", value: "Ativo"},
				            {text: "Inativo", value: "Inativo"}
						]},
						{type: "block", name:'nivel', list:[
							{type: "button", name: "save", value: "Salvar",inputTop:10,inputLeft:-30},
							{type: "button", position:'absolute',inputLeft:80,inputTop:16, name: "cancel", value: "Cancelar"}
						]},
					]}
				]},
			];
			new_user = myWins.window('new_user').attachForm(formStructure);
			if(id == 'new_user') {
				new_user.attachEvent("onButtonClick", function(name, command) {
					if(name == 'save') {
						alert('foi');
						new_user.send('<%= users_path(:method => :post) %>', function(loader, response){
							myWins.window('new_user').close();
							mygrid.updateFromXML('<%= users_path(:format =>:xml) %>');
						});
					}else if(name == 'cancel') {
						myWins.window('new_user').close();
					}
				});
			}else if(id == 'editar') {
				if(rowIdClicked == null) {
					rowIdClicked = mygrid.getSelectedId();
				}
				//Carrega os dados 
				new_user.load('/users/'+rowIdClicked);
				new_user.attachEvent("onButtonClick", function(name, command) {
						if(name == 'save') {
							this.send('<%= update_user_path(:method => :patch)  %>', function(loader, response){
								if(loader.xmlDoc.status == 400) {
									var erro = $.parseJSON(response)
									dhtmlx.alert({
										title:"Não foi possivel atualizar o registro.",
										type:"alert-error",
										text: erro.message
									});
								}else {
									var messagem = $.parseJSON(response)
									dhtmlx.message({
										text:messagem.message,
										expire:2000
									});
							      	myWins.window('new_user').close();
							      	mygrid.updateFromXML('<%= users_path(:format =>:xml) %>');
								}
								rowIdClicked = null;
					    });
						}else if(name == 'cancel') {
							myWins.window('new_user').close();
						}
					});
			}
			
		}else if(id== 'delete') {
			if(rowIdClicked == null) {
				rowIdClicked = mygrid.getSelectedId();
			}
			
			if(rowIdClicked > 0) {
				dhtmlx.confirm({
					title: "Tem certeza?",
					text: "Tem certeza que deseja remover este usuário?",
					callback: function(name) {
						if(name) {
							mygrid.deleteRow(rowIdClicked);
						}
					}
				});
			}else {
				dhtmlx.message({
					text:"Você não selecionou nenhum registro para excluir!",
					expire:2000
				});
			}
		}else if(id == 'desativar') {



			dhtmlx.message({
				text:"Usuário desativado!",
				expire:2000
			});
		}
 	}

</script>

<style>
	html, body, #gridbox, #contextArea {
		width: 100%;      /*provides the correct work of a full-screen layout*/
		height: 100%;     /*provides the correct work of a full-screen layout*/
		overflow: hidden; /*hides the default body's space*/
		margin: 0px;      /*hides the body's scrolls*/
	}
</style>
<div id="contextArea">
	<!--<div id="m1" text="File"> // the first top menu item-->
        <div id="editar" text="Editar"></div>
        <div id="delete" text="Excluir"></div> 
        <!-- <div id="ms1" type="separator"></div> // a separator    
        <div id="desativar" text="Desativar Usuário"></div> //the second child item -->  
     <!--</div>   -->
</div>

app/views/users_old/new.html.erb
<section class="content-header">
	<h1>Novo usuário</h1>
	<ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li><%= link_to users_path do %><i class="fa fa-users"></i> Usuarios<% end %></li>
        <li class="active fa fa-user">Novo</li>
    </ol>  
</section>
<section class="content">
	<div class="row">
		<div class="col-md-6">
			<%= render 'form' %>
		</div>
	</div>
</section>

app/views/users_old/show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>