config/routes.rb
Rails.application.routes.draw do

  get 'registros/verifica_servidor'

  resources :tipo_periodos
  resources :empresas
  resources :niveis do
    member do
      post "/update", :to => "niveis#update1", :as => 'update'
      post "/new_dia_nao_letivo", :to => "niveis#new_dia_nao_letivo", :as => 'new_dia_nao_letivo'
      post "/new_periodo_nao_letivo", :to => "niveis#new_periodo_nao_letivo", :as => 'new_periodo_nao_letivo'
      post "/delete_dia_nao_letivo/:id", :to => "niveis#delete_dia_nao_letivo", :as => 'delete_dia_nao_letivo'
      get 'periodo_nao_letivos', :to => "niveis#periodo_nao_letivos"
      get 'dias_nao_letivos', :to => "niveis#dias_nao_letivos"
      get 'periodos', :to => "niveis#periodos"
      get 'ferias', :to => "niveis#ferias"
      get 'tipo_periodos', :to => 'niveis#tipo_periodos'
      get 'series', :to =>'niveis#series'
    end
  end
  post '/niveis/new', :to =>'niveis#create', :as =>'nivel_new', :via => 'POST'
  resources :series do
    member do
      post "/update", :to => "series#update", :as => 'update'
      get 'turmas', :to =>'series#turmas', :as => 'series_turmas'
    end
  end
  post '/series/new', :to =>'series#create', :as =>'series_new', :via => 'POST'

  resources :turmas do

    member do
      get 'show_limited', :to => 'turmas#show'
      post '/alunos/import', :to =>'alunos#import_por_turma', :as =>'alunos_import', :via => 'POST'
      post "/update", :to => "turmas#update", :as => 'update'
      get 'alunos', :to => 'turmas#alunos'
      get 'aulas', :to => 'turmas#aulas'
      get 'dia_semana_aulas', :to => 'turmas#dia_semana_aulas'
      post '/new_aula', :to => 'turmas#new_aula'

    end

  end
  post '/turmas/new', :to =>'turmas#create', :as =>'turmas_new', :via => 'POST'
  get '/turmas/aula/:id_aula', :to => "turmas#aula"
  post '/update/aula', :to => "turmas#update_aula"
  resources :aulas do
  end

  resources :periodos do
    member do
      post "/update", :to => "periodos#update", :as => 'update'
    end
  end
  post '/periodos/new', :to =>'periodos#create', :as =>'periodos_new', :via => 'POST'

  resources :alunos do
    member do
      post "/update", :to => "alunos#update", :as => 'update'
      get '/historico', :to => "alunos#historico"
    end
  end
  #get '/all_alunos', :to => 'alunos#all_alunos', :as => 'all_alunos'
  post '/alunos/new', :to =>'alunos#create', :as =>'alunos_new', :via => 'POST'
  post '/alunos/import', :to =>'alunos#import', :as =>'alunos_import', :via => 'POST'
  get 'alunos_semturma', :to => 'alunos#alunos_semturma', :as => 'alunos_semturma'
  post 'adiciona_aluno_turma_path', :to => 'alunos#adiciona_aluno_turma', :as => 'adiciona_aluno_turma'

  resources :etiquetas do
    member do

    end

  end
  get '/etiquetas_por_aluno/:aluno_id', :to => "etiquetas#etiquetas_por_aluno", :as => "etiquetas_por_aluno"

  devise_for :users, :path_prefix => 'devise', :skip => [:api, :registros]
  devise_scope :user do
    get '/logout',  :to => 'devise/sessions#destroy'
  end
  resources :users do
    member do
      
    end
  end
  post 'update_user', :to => 'users#update', :as => 'update_user'
  
  resources :dashboard
  get 'calendario' => 'dashboard#calendario'

  resources :registros

  root 'dashboard#index'
  get 'menu_xml' => 'menu#menu_xml'
  get 'horas' => 'menu#horas'
  get 'minutos' => 'menu#minutos'
  get 'niveis_toolbar' => 'niveis#niveis_toolbar'
  get 'admin' => 'dashboard#admin'

  match "tipo_periodos/db_action", :to => "tipo_periodos#db_action", :as => "tipo_periodos_db_action", :via =>"post"
  match "users/db_action", :to => "users#db_action", :as => "users_db_action", :via =>"post"
  match "alunos/db_action", :to => "alunos#db_action", :as => "alunos_db_action", :via =>"post"
  match "etiquetas/db_action", :to => "etiquetas#db_action", :as => "etiquetas_db_action", :via =>"post"
  match "niveis/db_action", :to => "niveis#db_action", :as => "niveis_db_action", :via =>"post"
  match "series/db_action", :to => "series#db_action", :as => "series_db_action", :via =>"post"
  match "turmas/db_action", :to => "turmas#db_action", :as => "turmas_db_action", :via =>"post"
  match "turmas/db_action_alunos", :to => "turmas#db_action_alunos", :as => "turmas_db_action_alunos", :via =>"post"
  match "turmas/db_action_aulas", :to => "turmas#db_action_aulas", :as => "turmas_db_action_aulas", :via =>"post"
  match "niveis/db_action_dias_nao_letivos", :to => "niveis#db_action_dias_nao_letivos", :as => "niveis_db_action_dias_nao_letivos", :via =>"post"
  match "niveis/db_action_periodo_nao_letivos", :to => "niveis#db_action_periodo_nao_letivos", :as => "niveis_db_action_periodo_nao_letivos", :via =>"post"
  match "niveis/db_action_periodos", :to => "niveis#db_action_periodos", :as => "niveis_db_action_periodos", :via =>"post"




  #Api
  namespace :api do
    root 'api#index'
    resources :registros do
      #match "upload_file", :to => "registros#upload_file", :via => "post"
      collection do
        get "upload_file"
        post "upload_file"
        post "upload_file_line"
      end
    end
  end

  namespace :mobile do

  end
end

app/controllers/niveis_controller.rb
class NiveisController < ApplicationController
  before_action :set_registro, only: [:show, :edit, :update, :destroy, :update1, :dias_nao_letivos, :periodo_nao_letivos, :periodos]
  before_action :set_listagem, only: [:index]
  respond_to :html, :xml, :json
  protect_from_forgery :except => [:create, :db_action_dias_nao_letivos, :update1, :new_dia_nao_letivo, :new_periodo_nao_letivo,
      :new_periodo,:db_action, :db_action_periodos, :db_action_periodo_nao_letivos, :db_action_periodos]
  def index
    respond_with(@niveis)
  end
  def niveis_toolbar
    respond_with()
  end

  def new
    @nivel = Nivel.new
    #@nivel.create_dias_nao_letivo
    @nivel.dias_nao_letivos.build
  end

  def edit
    @nivel.dias_nao_letivos.build
    respond_with(@nivel)
  end

  def create
    #logger.debug nivel_params
    #return false
    @nivel = Nivel.new(nivel_params)
    @nivel.save
    #logger.debug
    #return false
    respond_to do |format|
      format.html { render 'new', notice: 'Erro ao cadastradar!'}
    end
  end

  def update1
    logger.info 'entoru no update info'
    @nivel.update(nivel_params)
  end

  def update
    if(@nivel.update(nivel_params))
      respond_to do |format|
        if (request.format == 'text/html')
          format.html {redirect_to niveis_path, notice: 'Usuário atualizado com sucesso!'}
        else
          format.html { render 'edit', notice: 'Erro ao atualizar'}
        end
      end
    else
      respond_to do |format|
        format.json { render json: {:errors => @user.errors}, status: 422}
        format.html { render 'edit', notice: 'Erro ao cadastradar!'}
      end
    end
  end

  def db_action
    logger.info 'entoru no destroy'
    logger.info params
    @mode = params["!nativeeditor_status"]
    logger.info @mode
    case @mode
    when "inserted"
        logger.info 'Inserted'

    when "deleted"
      @record = Nivel.find(params[:gr_id])
      @record.destroy
    end
  end



  def db_action_dias_nao_letivos
    logger.info 'Entrou db_action'
    logger.info params
    @mode = params["!nativeeditor_status"]
    logger.info @mode

    case @mode
    when "inserted"
        logger.info 'Inserted'

    when "deleted"
      @record = DiasNaoLetivo.find(params[:gr_id])
      @record.destroy
    when "updated"
        logger.info 'Updated'
    end
  end


  def dias_nao_letivos
    #logger.info ' Dias não letivos método'
    #logger.info params[:id]
    @dias_nao_letivos = DiasNaoLetivo.all.where(nivel: params[:id])
    #logger.info @dias_nao_letivos.inspect
  end
  def ferias
    #@ferias = DiasNaoLetivo.all.where(nivel: params[:id])
    #logger.info @dias_nao_letivos.inspect
  end

  def new_dia_nao_letivo
    @novo = DiasNaoLetivo.new(dias_nao_letivos_params)
    if(@novo.save)
      respond_to do |format|
         format.json { render json: {:message => 'Cadastrado com sucesso!'}, status: 200}
      end
    end
  end

  #def delete_dia_nao_letivo
  #  @dia = DiasNaoLetivo.all.where(id: params[:id])
  #end
  def new_periodo_nao_letivo
    @novo = PeriodoNaoLetivo.new(periodo_nao_letivos_params)
    if(@novo.save)
      respond_to do |format|
         format.json { render json: {:message => 'Cadastrado com sucesso!'}, status: 200}
      end
    end
  end
  def periodo_nao_letivos
    logger.info 'entrou no periodo nao letivo'
    @periodo_nao_letivos = PeriodoNaoLetivo.all.where(nivel: params[:id])
  end

  def db_action_periodo_nao_letivos
    logger.info 'Entrou db_action'
    logger.info params
    @mode = params["!nativeeditor_status"]
    logger.info @mode

    case @mode
    when "inserted"
        logger.info 'Inserted'

    when "deleted"
      @record = PeriodoNaoLetivo.find(params[:gr_id])
      @record.destroy

    when "updated"
        logger.info 'Updated'
    end
  end

  #Parte de periodos
  def periodos
    @periodos = Periodo.all.where(nivel: params[:id])
  end
  def db_action_periodos
    @mode = params["!nativeeditor_status"]
    case @mode
    when "deleted"
      @record = Periodo.find(params[:gr_id])
      @record.destroy
    end
  end
  #encerra parte de periodos

  #Parte dos tipo de periodos
  def tipo_periodos
    @tipo_periodos = TipoPeriodo.all.where('id not in (?)',Periodo.all.where(nivel: params[:id]).select(:tipo_periodo_id))
  end
  #encerra parte de periodos


  #series deste nivel
  def series

    @series = Serie.all.where(nivel: params[:id] )
    respond_with(@series)
  end

  private
  def set_listagem
    @niveis = Nivel.all.order(:created_at)
  end

  def set_registro
    @nivel = Nivel.find(params[:id])
  end

  def nivel_params
    params.permit(:id, :titulo, :descricao, :dias_semana_letivo, :created_at, :updated_at,
            {:dias_nao_letivos_attributes => [:id, :nivel_id, :motivo, :dia]})
  end
  def dias_nao_letivos_params
    params.permit(:motivo, :dia, :nivel_id, :created_at, :updated_at)
  end
  def periodo_nao_letivos_params
    params.permit(:descricao, :inicio,:termino, :nivel_id, :created_at, :updated_at)
  end
end

app/helpers/niveis_helper.rb
module NiveisHelper
end

app/views/niveis/db_action.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<data>
	<action type="<%= @mode %>" sid="<%= @record.id %>" tid="<%= @tid %>" />
</data>

app/views/niveis/db_action_dias_nao_letivos.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<data>
	<action type="<%= @mode %>" sid="<%= @record.id %>" tid="<%= @tid %>" />
</data>

app/views/niveis/db_action_periodo_nao_letivos.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<data>
	<action type="<%= @mode %>" sid="<%= @record.id %>" tid="<%= @tid %>" />
</data>

app/views/niveis/db_action_periodos.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<data>
	<action type="<%= @mode %>" sid="<%= @record.id %>" tid="<%= @tid %>" />
</data>

app/views/niveis/dias_nao_letivos.html.erb
<script>
	dhtmlxEvent(window,"load", function(id){
		//var layout = new dhtmlXLayoutObject(document.body, "2E");
		var layout = new dhtmlXLayoutObject('layout_dias_nao_letivos', "1C");
		layout.cells("a").hideHeader();
		
		
		mygrid = layout.cells("a").attachGrid();
		mygrid.load("dias_nao_letivos.xml",'xml');
		mygrid.setColumnIds("id,motivo,dia");
		mygrid.enableAutoWidth(true);
		mygrid.enableEditEvents(false,false,false);
		mygrid.init();
		
		toolbar = new dhtmlXToolbarObject({
    		parent:"my_toolbar_here",
    		icons_path: "/assets/dhtmlx/",
		    items:[
		        {id: "new", type: "button", text: "Novo", img: "new.gif"},
		        {id: "delete", type: "button", text:'Excluir', img: "trash_delete.gif"},
		    ],
		    onClick:function(id){
		    	if(id == 'new') {
		    		var myWins= new dhtmlXWindows();
		    		
		    		myWins.createWindow('new_dia_nao_letivo', 50, 25, 360,250);
		    		myWins.window('new_dia_nao_letivo').setText('Novo registro');
		    		myWins.window('new_dia_nao_letivo').setModal(true);
		    		myWins.window('new_dia_nao_letivo').denyResize();
		    		myWins.window('new_dia_nao_letivo').denyPark();
		    		
		    		formStructure = [
					    {type:"settings",position:"label-top"},
					    {type: "block", name:'nivel', list:[
						    {type: "fieldset",name:"nivel", width:300, label: "Novo registro", list:[
						        {type: "hidden", name: 'nivel_id', value: '<%= @nivel.id %>'},
						        {type: "input", width: 200, name: 'motivo', label: 'Motivo:', validate: "NotEmpty", required: true},
						        {type:"calendar", width: 200, name:"dia",dateFormat:'%d-%m-%Y', label:"Data",readonly:true, validate: "NotEmpty", required: true},
								{type: "block", name:'nivel', list:[
									{type: "button", inputLeft: -25, name: "save", value: "Adicionar"},
									{type: "button", position:'absolute',inputLeft:85,inputTop:6, name: "cancel", value: "Cancelar"},
								]},
						    ]}
						 ]},
					];
					
		    		new_register = myWins.window('new_dia_nao_letivo').attachForm(formStructure);
		    		new_register.attachEvent("onButtonClick", function(name, command) {
						if(name == 'save') {
							//alert(new_register.validate());
							console.log('Vai salvar novo registro e atualizar tabela');
							this.send('<%= new_dia_nao_letivo_nivel_path(@nivel) %>', function(loader, response){
					            myWins.window('new_dia_nao_letivo').close();
					            mygrid.updateFromXML('dias_nao_letivos.xml');
					        });
							
						}else if(name == 'cancel') {
							console.log('cancelar cadastro');
							myWins.window('new_dia_nao_letivo').close();
						}
					});
		    		
		    	}else if(id == 'delete') {
		    		var selectedRow = mygrid.getSelectedId();
		    		if(selectedRow > 0) {
						dhtmlx.confirm({
						    title: "Tem certeza?",
						    text: "Você tem certeza que deseja excluir este registo??",
						    callback: function(name) {
						    	if(name) {					    		
						    		mygrid.deleteSelectedItem();
						    	}
						    }
						});
					}else {
						dhtmlx.message({
						    text:"Você não selecionou nenhum registro para excluir!",
						    expire:1000
						});
					}
		    	}
		    }
		});
		dp = new dataProcessor('<%= niveis_db_action_dias_nao_letivos_path %>');
		dp.init(mygrid);
		dp.setTransactionMode("POST");
		//dp.setTransactionMode("GET", false);
		dp.enableDataNames(true);
		
	});
</script>
<style>
	html, body, #layout_dias_nao_letivos {
	        width: 100%;      /*provides the correct work of a full-screen layout*/ 
	        height: 100%;     /*provides the correct work of a full-screen layout*/
	        overflow: hidden; /*hides the default body's space*/
	        margin: 0px;      /*hides the body's scrolls*/
	    }
</style>
<div id='my_toolbar_here' style="width: 100%;"></div>
<div id="layout_dias_nao_letivos"></div>

app/views/niveis/edit.html.erb
<%= csrf_meta_tags %>
<script>
	var layout;
	var myForm;
	dhtmlxEvent(window,"load", function(id){
		//var layout = new dhtmlXLayoutObject(document.body, "2E");
		layout = new dhtmlXLayoutObject(document.body, "1C");
		
		mygrid =  layout.cells("a").attachGrid();
		mygrid.init();
		//layout.cells("a").setText("Detalhes da série");//sets the form's header

		var tabbar = layout.cells("a").attachTabbar({
			icons_path: "/assets/dhtmlx/"
		});
		var tab = tabbar.addTab(
	    'detalhes_nivel',       // id
	    'Detalhes do nivel',    // tab text
	    null,       // auto width
	    null,       // last position
	    false,      // inactive
	    false       // disable close button <-- this one
		);
		//Seta a tab como ativa
		tabbar.tabs('detalhes_nivel').setActive();

		myToolbar = tabbar.tabs("detalhes_nivel").attachToolbar({
			icons_path: "/assets/dhtmlx/",
		    items:[
		        {id: "save", type: "button", text: "Salvar alterações", img: "new.gif"},
		    ],
		     onClick:function(id){
		    	if(id == 'save') {
		    		salvar_alteracoes();
		    	}
		    }

		});
		
		//Configura o formulario
		formStructure = [
		    {type:"settings",position:"label-top"},
		    {type: "block", width: 900, name:'nivel', list:[
			    {type: "fieldset",name:"nivel", width:900, label: "Detalhes", list:[
			        {type: "hidden", name: 'id'},
			        {type: "input", width: 300, name: 'titulo', label: 'Titulo:'},
			        {type:"input", width: 300, name:"descricao", label:"Descrição:"},
			        {type:"multiselect",label:"Dias de aula:", name:'dias_semana_letivo', inputHeight:130,inputWidth:130,
					      options:[
					        {text: "Domingo", value: "0"},
					        {text: "Segunda-feira", value: "1"},
					        {text: "Terça-feira", value: "2"},
					        {text: "Quarta-feira", value: "3"},
					        {text: "Quinta-feira", value: "4"},
					        {text: "Sexta-feira", value: "5"},
					        {text: "Sabado", value: "6"}
					]},
					{type:"container", name:"periodos", label:"Periodos", inputWidth:500, inputHeight:400},
					{type:"container", name:"dias_naoletivos", label:"Dias não letivos", inputWidth:500, inputHeight:400},
					{type:"container", name:"periodo_nao_letivos", label:"Calendario de férias", inputWidth:500, inputHeight:400},
					{type: "button", name: "save", value: "Salvar mudanças"},
			    ]}
			 ]}
		];


		//Adiciona a tab com o formulario
		myForm = tabbar.cells('detalhes_nivel').attachForm(formStructure);
		myForm.attachEvent("onButtonClick", function(name, command) {
			if(name == 'save') {
				salvar_alteracoes();				
			}
		});
		
		//Carrega os dados no formulario
		myForm.load('<%= edit_nivel_path(@nivel, :format => 'xml')  %>');
		
		
		//Periodos
		periodos = new dhtmlXLayoutObject(myForm.getContainer("periodos"),"1C");
		periodos.cells('a').hideHeader();
		periodos.cells('a').attachURL('periodos');


		//Dias não letivos
		dias_nao_letivos = new dhtmlXLayoutObject(myForm.getContainer("dias_naoletivos"),"1C");
		dias_nao_letivos.cells('a').hideHeader();
		dias_nao_letivos.cells('a').attachURL('dias_nao_letivos');
		
		//Calendario de férias(perido_nao_letivos)
		ferias = new dhtmlXLayoutObject(myForm.getContainer("periodo_nao_letivos"),"1C");
		ferias.cells('a').hideHeader();
		ferias.cells('a').attachURL('periodo_nao_letivos');
				 
		 var tab_listagem = tabbar.addTab(
		    'lista_series',       // id
		    'Lista de series',    // tab text
		    null,       // auto width
		    null,       // last position
		    false,      // inactive
		    false       // disable close button <-- this one
		);
		
		
		mygrid =  tabbar.cells("lista_series").attachGrid();
		mygrid.load("series.xml",'xml');
		mygrid.enableAutoWidth(true);
		mygrid.enableEditEvents(false,false,false);
		mygrid.init();
		
		dp = new dataProcessor('<%= series_db_action_path %>');
		dp.init(mygrid);
		dp.setTransactionMode("POST");
		//dp.setTransactionMode("GET", false);
		dp.enableDataNames(true);
		
		
		toolbar_grid = tabbar.cells("lista_series").attachToolbar({
    		icons_path: "/assets/dhtmlx/",
		    items:[
		    	{id: "new_serie", type: "button", text: "Nova série ", img: "new.gif"},
		        {id: "separator", type: "separator"},
		        {id: "delete_serie", type: "button", text:'Excluir', img: "trash_delete.gif"},
		    ],
		    onClick:function(id){
		    	if(id == 'new_serie') {
		    	 	var myWins= new dhtmlXWindows();    	 	
		    	 	myWins.createWindow('new_serie', 240, 75, 360,180);
		    		myWins.window('new_serie').setText('Novo registro');
		    		myWins.window('new_serie').setModal(true);
		    		myWins.window('new_serie').denyResize();
		    		myWins.window('new_serie').denyPark();
		    		
		    		formStructure = [
					    {type:"settings",position:"label-top"},
					    {type: "block", name:'nivel', list:[
						    {type: "fieldset",name:"nivel", width:300, label: "Novo registro", list:[
						        {type: "hidden", name: 'nivel_id', value: '<%= @nivel.id %>'},
						        {type: "input", width: 200, name: 'titulo', label: 'Titulo:', validate: "NotEmpty", required: true},
								{type: "block", name:'nivel', list:[
									{type: "button", inputLeft: -25, name: "save", value: "Adicionar"},
									{type: "button", position:'absolute',inputLeft:85,inputTop:6, name: "cancel", value: "Cancelar"},
								]},
						    ]}
						 ]},
					];
					
		    		new_register = myWins.window('new_serie').attachForm(formStructure);
		    		new_register.attachEvent("onButtonClick", function(name, command) {
						if(name == 'save') {
							//alert(new_register.validate());
							this.send('<%= series_new_path(:method => :post) %>', function(loader, response){
					            myWins.window('new_serie').close();
					            mygrid.updateFromXML('series.xml');
					            parent.atualiza_menu();
					        });					        
						}else if(name == 'cancel') {
							myWins.window('new_serie').close();
						}
					});
		    	 }else if (id == 'delete_serie') {
					var selectedRow = mygrid.getSelectedId();
			    	if(selectedRow > 0) {
						dhtmlx.confirm({
						    title: "Tem certeza?",
						    text: "Você tem certeza que deseja excluir esta série? Todas as turmas e aulas associadas a ela serão excluidas",
						    callback: function(name) {
						    	if(name) {
						    		dhtmlx.confirm({
									    title: "Tem certeza?",
									    text: "Lembre que esta ação não podera ser desfeita, esta série e todos as turmas e aulas associadas a ela serão apagados definitivamente.",
									    callback: function(name) {
									    	if(name) {
									    		mygrid.deleteSelectedItem();		    		
										    	parent.atualiza_menu();
									    	}
									    }
									});
						    	}
						    }
						});
					}else {
						dhtmlx.message({
						    text:"Você não selecionou nenhum registro para excluir!",
						    expire:2000
						});
					}
					
				}
    		}
		});
	});
	function salvar_alteracoes() {
		myForm.send('<%= update_nivel_path(@nivel) %>', function(loader, response) {
			dhtmlx.message({
			    text:"Registro atualizado com sucesso!",
			    expire:1000
			});
		});
		parent.atualiza_menu();
	}
</script>
<style>
	html, body, #gridbox {
	        width: 100%;      /*provides the correct work of a full-screen layout*/ 
	        height: 100%;     /*provides the correct work of a full-screen layout*/
	        overflow: hidden; /*hides the default body's space*/
	        margin: 0px;      /*hides the body's scrolls*/
	    }
</style>
<header><div id="niveis_menuObj"></div></header>

<div id="gridbox"></div>  
<div id='form_container'></div>

<!--
<section class="content-header">
	<h1>Novo nivel</h1>
	<ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li><%= link_to niveis_path do %><i class="fa fa-users"></i> Niveis<% end %></li>
        <li class="active fa fa-user">Novo</li>
    </ol>  
</section>
<section class="content">
	<div class="row">
		<div class="col-md-6">
			<%= render 'form' %>
		</div>
	</div>
</section>
-->

app/views/niveis/new.html.erb
<section class="content-header">
	<h1>Novo nivel</h1>
	<ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li><%= link_to niveis_path do %><i class="fa fa-users"></i> Niveis<% end %></li>
        <li class="active fa fa-user">Novo</li>
    </ol>  
</section>
<section class="content">
	<div class="row">
		<div class="col-md-6">
			<%= render 'form' %>
		</div>
	</div>
</section>

app/views/niveis/update1.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<data>
	<action type="<%= @mode %>" sid="<%= @id %>" tid="<%= @tid %>" />
</data>