config/routes.rb
Rails.application.routes.draw do

  get 'registros/verifica_servidor'

  resources :tipo_periodos
  resources :empresas
  resources :niveis do
    member do
      post "/update", :to => "niveis#update1", :as => 'update'
      post "/new_dia_nao_letivo", :to => "niveis#new_dia_nao_letivo", :as => 'new_dia_nao_letivo'
      post "/new_periodo_nao_letivo", :to => "niveis#new_periodo_nao_letivo", :as => 'new_periodo_nao_letivo'
      post "/delete_dia_nao_letivo/:id", :to => "niveis#delete_dia_nao_letivo", :as => 'delete_dia_nao_letivo'
      get 'periodo_nao_letivos', :to => "niveis#periodo_nao_letivos"
      get 'dias_nao_letivos', :to => "niveis#dias_nao_letivos"
      get 'periodos', :to => "niveis#periodos"
      get 'ferias', :to => "niveis#ferias"
      get 'tipo_periodos', :to => 'niveis#tipo_periodos'
      get 'series', :to =>'niveis#series'
    end
  end
  post '/niveis/new', :to =>'niveis#create', :as =>'nivel_new', :via => 'POST'
  resources :series do
    member do
      post "/update", :to => "series#update", :as => 'update'
      get 'turmas', :to =>'series#turmas', :as => 'series_turmas'
    end
  end
  post '/series/new', :to =>'series#create', :as =>'series_new', :via => 'POST'

  resources :turmas do

    member do
      get 'show_limited', :to => 'turmas#show'
      post '/alunos/import', :to =>'alunos#import_por_turma', :as =>'alunos_import', :via => 'POST'
      post "/update", :to => "turmas#update", :as => 'update'
      get 'alunos', :to => 'turmas#alunos'
      get 'aulas', :to => 'turmas#aulas'
      get 'dia_semana_aulas', :to => 'turmas#dia_semana_aulas'
      post '/new_aula', :to => 'turmas#new_aula'

    end

  end
  post '/turmas/new', :to =>'turmas#create', :as =>'turmas_new', :via => 'POST'
  get '/turmas/aula/:id_aula', :to => "turmas#aula"
  post '/update/aula', :to => "turmas#update_aula"
  resources :aulas do
  end

  resources :periodos do
    member do
      post "/update", :to => "periodos#update", :as => 'update'
    end
  end
  post '/periodos/new', :to =>'periodos#create', :as =>'periodos_new', :via => 'POST'

  resources :alunos do
    member do
      post "/update", :to => "alunos#update", :as => 'update'
      get '/historico', :to => "alunos#historico"
    end
  end
  #get '/all_alunos', :to => 'alunos#all_alunos', :as => 'all_alunos'
  post '/alunos/new', :to =>'alunos#create', :as =>'alunos_new', :via => 'POST'
  post '/alunos/import', :to =>'alunos#import', :as =>'alunos_import', :via => 'POST'
  get 'alunos_semturma', :to => 'alunos#alunos_semturma', :as => 'alunos_semturma'
  post 'adiciona_aluno_turma_path', :to => 'alunos#adiciona_aluno_turma', :as => 'adiciona_aluno_turma'

  resources :etiquetas do
    member do

    end

  end
  get '/etiquetas_por_aluno/:aluno_id', :to => "etiquetas#etiquetas_por_aluno", :as => "etiquetas_por_aluno"

  devise_for :users, :path_prefix => 'devise', :skip => [:api, :registros]
  devise_scope :user do
    get '/logout',  :to => 'devise/sessions#destroy'
  end
  resources :users do
    member do
      
    end
  end
  post 'update_user', :to => 'users#update', :as => 'update_user'
  
  resources :dashboard
  get 'calendario' => 'dashboard#calendario'

  resources :registros

  root 'dashboard#index'
  get 'menu_xml' => 'menu#menu_xml'
  get 'horas' => 'menu#horas'
  get 'minutos' => 'menu#minutos'
  get 'niveis_toolbar' => 'niveis#niveis_toolbar'
  get 'admin' => 'dashboard#admin'

  match "tipo_periodos/db_action", :to => "tipo_periodos#db_action", :as => "tipo_periodos_db_action", :via =>"post"
  match "users/db_action", :to => "users#db_action", :as => "users_db_action", :via =>"post"
  match "alunos/db_action", :to => "alunos#db_action", :as => "alunos_db_action", :via =>"post"
  match "etiquetas/db_action", :to => "etiquetas#db_action", :as => "etiquetas_db_action", :via =>"post"
  match "niveis/db_action", :to => "niveis#db_action", :as => "niveis_db_action", :via =>"post"
  match "series/db_action", :to => "series#db_action", :as => "series_db_action", :via =>"post"
  match "turmas/db_action", :to => "turmas#db_action", :as => "turmas_db_action", :via =>"post"
  match "turmas/db_action_alunos", :to => "turmas#db_action_alunos", :as => "turmas_db_action_alunos", :via =>"post"
  match "turmas/db_action_aulas", :to => "turmas#db_action_aulas", :as => "turmas_db_action_aulas", :via =>"post"
  match "niveis/db_action_dias_nao_letivos", :to => "niveis#db_action_dias_nao_letivos", :as => "niveis_db_action_dias_nao_letivos", :via =>"post"
  match "niveis/db_action_periodo_nao_letivos", :to => "niveis#db_action_periodo_nao_letivos", :as => "niveis_db_action_periodo_nao_letivos", :via =>"post"
  match "niveis/db_action_periodos", :to => "niveis#db_action_periodos", :as => "niveis_db_action_periodos", :via =>"post"




  #Api
  namespace :api do
    root 'api#index'
    resources :registros do
      #match "upload_file", :to => "registros#upload_file", :via => "post"
      collection do
        get "upload_file"
        post "upload_file"
        post "upload_file_line"
      end
    end
  end

  namespace :mobile do

  end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :set_registro, only: [:show, :edit, :update, :destroy, :update1, :dias_nao_letivos, :periodo_nao_letivos]
  before_action :set_listagem, only: [:index]
  respond_to :html, :xml, :json
  protect_from_forgery :except => [:create, :update, :db_action]

  def index
      respond_with(@turmas)
  end

  def new
    @serie = Serie.new(series_params)
  end
  def show

  end

  def edit
    #@nivel.dias_nao_letivos.build
      respond_with(@serie)
  end

  def create
    #logger.debug nivel_params
    @record = Serie.new(series_params)
    logger.debug @record.inspect
    if(@record.save)
      respond_to do |format|
         format.json { render json: {:message => 'Cadastrado com sucesso!'}, status: 200}
      end
    end
    #respond_to do |format|
    #  format.html { render 'new', notice: 'Erro ao cadastradar!'}
    #end
  end

  def update
    logger.info 'entoru no update info'
    if(@serie.update(series_params))
      respond_to do |format|
         format.json { render json: {:message => 'Atualizado com sucesso!'}, status: 200}
      end
    end
  end

  def db_action
    @mode = params["!nativeeditor_status"]
    case @mode
    when "inserted"

    when "deleted"
      @record = Serie.find(params[:gr_id])
      @record.destroy
    end
  end

  def turmas
    @turmas = Turma.all.where(serie: params[:id] )
    respond_with(@turmas)
  end

  #def db_action_dias_nao_letivos
  #  logger.info 'Entrou db_action'
  #  logger.info params
  #  @mode = params["!nativeeditor_status"]
  #  logger.info @mode

  #  case @mode
  #  when "inserted"
  #      logger.info 'Inserted'

  #  when "deleted"
  #    @record = DiasNaoLetivo.find(params[:gr_id])
  #    @record.destroy
  #  when "updated"
  #      logger.info 'Updated'
  #  end
  #end

  #end
  #def new_periodo_nao_letivo
  #  @novo = PeriodoNaoLetivo.new(periodo_nao_letivos_params)
  #  if(@novo.save)
  #    respond_to do |format|
  #       format.json { render json: {:message => 'Cadastrado com sucesso!'}, status: 200}
  #    end
  #  end
  #end
  #def periodo_nao_letivos
  #  logger.info 'entrou no periodo nao letivo'
  #  @periodo_nao_letivos = PeriodoNaoLetivo.all.where(nivel: params[:id])
  #end

  private
  def set_listagem
    @niveis = Serie.all.order(:created_at)
  end

  def set_registro
    @serie = Serie.find(params[:id])
  end

  def series_params
    params.permit(:titulo, :nivel_id, :created_at, :updated_at)
  end
end

app/views/series/db_action.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<data>
	<action type="<%= @mode %>" sid="<%= @record.id %>" tid="<%= @tid %>" />
</data>

app/views/series/show.html.erb
<%= csrf_meta_tags %>
<script>
	dhtmlxEvent(window,"load", function(id){
		//var layout = new dhtmlXLayoutObject(document.body, "2E");
		var layout = new dhtmlXLayoutObject(document.body, "1C");

		//layout.cells("a").setText("Detalhes da série");//sets the form's header
		var tabbar = layout.cells("a").attachTabbar({
			icons_path: "/assets/dhtmlx/"
		});
		var tab = tabbar.addTab(
	    'detalhes_serie',       // id
	    'Detalhes da série',    // tab text
	    null,       // auto width
	    null,       // last position
	    false,      // inactive
	    false       // disable close button <-- this one
		);
		//Seta a tab como ativa
		tabbar.tabs('detalhes_serie').setActive();
		//Configura o formulario
		formStructure = [
		    {type:"settings",position:"label-top"},
		    {type: "block", width: 900, name:'nivel', list:[
			    {type: "fieldset",name:"nivel", width:900, label: "Detalhes", list:[
			        {type: "hidden", name: 'id'},
			        {type: "input", width: 300, name: 'titulo', label: 'Titulo:'},
					{type: "button", name: "save", value: "Salvar mudanças"},
			    ]}
			 ]}
		];

		//Adiciona a tab com o formulario
		myForm = tabbar.cells('detalhes_serie').attachForm(formStructure);
		myForm.attachEvent("onButtonClick", function(name, command) {
			if(name == 'save') {
				//dp.setDataColumns(['nivel',true,true,true]);
				//dp.sendData('nivel');
				//myForm.send('update');
				this.send('<%= update_series_path(@serie) %>', function(loader, response) {
					dhtmlx.message({
					    text:"Registro atualizado com sucesso!",
					    expire:2000
					});
				});
				//parent.myTree.loadOpenStates('aqa');
				parent.atualiza_menu();

			}
		});

		//Carrega os dados no formulario
		myForm.load('<%= edit_series_path(@serie, :format => 'xml')  %>');

		var tab_listagem = tabbar.addTab(
		    'lista_turmas',       // id
		    'Lista de turmas',    // tab text
		    null,       // auto width
		    null,       // last position
		    false,      // inactive
		    false       // disable close button <-- this one
		);


		mygrid =  tabbar.cells("lista_turmas").attachGrid();
		mygrid.load('<%= series_turmas_series_path(@serie, :format => 'xml') %>','xml');
		mygrid.enableAutoWidth(true);
		mygrid.enableEditEvents(false,false,false);
		mygrid.init();

		dp = new dataProcessor('<%= turmas_db_action_path %>');
		dp.init(mygrid);
		dp.setTransactionMode("POST");
		//dp.setTransactionMode("GET", false);
		dp.enableDataNames(true);


		toolbar_grid = tabbar.cells("lista_turmas").attachToolbar({
    		icons_path: "/assets/dhtmlx/",
		    items:[
		    		{id: "new_turma", type: "button", text: "Nova turma", img: "new.gif"},
		        {id: "delete_turma", type: "button", text:'Excluir', img: "trash_delete.gif"},
		    ],
		    onClick:function(id){
		    	if(id == 'new_turma') {
		    	 	var myWins= new dhtmlXWindows();
		    	 	myWins.createWindow('new_turma', 240, 75, 360,180);
		    		myWins.window('new_turma').setText('Novo registro');
		    		myWins.window('new_turma').setModal(true);
		    		myWins.window('new_turma').denyResize();
		    		myWins.window('new_turma').denyPark();

		    		formStructure = [
					    {type:"settings",position:"label-top"},
					    {type: "block", name:'nivel', list:[
						    {type: "fieldset",name:"nivel", width:300, label: "Novo registro", list:[
						        {type: "hidden", name: 'serie_id', value: '<%= @serie.id %>'},
						        {type: "input", width: 200, name: 'titulo', label: 'Titulo:', validate: "NotEmpty", required: true},
								{type: "block", name:'nivel', list:[
									{type: "button", inputLeft: -25, name: "save", value: "Adicionar"},
									{type: "button", position:'absolute',inputLeft:85,inputTop:6, name: "cancel", value: "Cancelar"},
								]},
						    ]}
						 ]},
					];

		    		new_register = myWins.window('new_turma').attachForm(formStructure);
		    		new_register.attachEvent("onButtonClick", function(name, command) {
						if(name == 'save') {
							//alert(new_register.validate());
							this.send('<%= turmas_new_path(:method => :post) %>', function(loader, response){
					           myWins.window('new_turma').close();
					           mygrid.updateFromXML('<%= series_turmas_series_path(@serie, :format => 'xml') %>');
					           parent.atualiza_menu();
					        });



						}else if(name == 'cancel') {
							myWins.window('new_turma').close();
						}
					});


		    	 }else if (id == 'delete_turma') {
					var selectedRow = mygrid.getSelectedId();
			    	if(selectedRow > 0) {
						dhtmlx.confirm({
						    title: "Tem certeza?",
						    text: "Você tem certeza que deseja excluir esta turma? Todas as aulas associadas a ela serão excluidas",
						    callback: function(name) {
						    	if(name) {
						    		dhtmlx.confirm({
									    title: "Tem certeza?",
									    text: "Lembre que esta ação não podera ser desfeita, esta turma e todos as aulas e aulnos associadas a ela serão perdidos.",
									    callback: function(name) {
									    	if(name) {
									    		mygrid.deleteSelectedItem();
										    	parent.atualiza_menu();
									    	}
									    }
									});
						    	}
						    }
						});
					}else {
						dhtmlx.message({
						    text:"Você não selecionou nenhum registro para excluir!",
						    expire:2000
						});
					}

				}
    		}
		});

	});
</script>
<style>
	html, body, #gridbox {
	        width: 100%;      /*provides the correct work of a full-screen layout*/
	        height: 100%;     /*provides the correct work of a full-screen layout*/
	        overflow: hidden; /*hides the default body's space*/
	        margin: 0px;      /*hides the body's scrolls*/
	    }
</style>

<div id="gridbox"></div>
<div id='form_container'></div>